# Task
Estrai i dati dei primi 12 pazienti dal file "dataset_1.zip" situato nella cartella "lab 1" all'interno della sezione "Condivisi con me" del mio Google Drive.

## Monta google drive

### Subtask:
Monta Google Drive per accedere ai file memorizzati.

**Reasoning**:
Mount Google Drive to access files stored in the user's Drive.

In [ ]:
# Clean reinstall of compatible versions
!pip uninstall -y numpy SimpleITK PyWavelets pyradiomics
!pip install numpy==1.26.4 SimpleITK==2.3.1 PyWavelets==1.6.0

!pip install git+https://github.com/AIM-Harvard/pyradiomics.git
# restart session

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: SimpleITK 2.3.1
Uninstalling SimpleITK-2.3.1:
  Successfully uninstalled SimpleITK-2.3.1
Found existing installation: PyWavelets 1.6.0
Uninstalling PyWavelets-1.6.0:
  Successfully uninstalled PyWavelets-1.6.0
Found existing installation: pyradiomics 3.1.1.dev111+g8ed579383
Uninstalling pyradiomics-3.1.1.dev111+g8ed579383:
  Successfully uninstalled pyradiomics-3.1.1.dev111+g8ed579383
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting SimpleITK==2.3.1
  Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.9 kB)
Collecting PyWavelets==1.6.0
  Using cached pywavelets-1.6.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (52.7 MB)
Using cached pywavelets-1.6.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
Installing collected packages: SimpleITK, numpy, PyWavelets
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed PyWavelets-1.6.0 SimpleITK-2.3.1 numpy-1.26.4

Collecting git+https://github.com/AIM-Harvard/pyradiomics.git
  Cloning https://github.com/AIM-Harvard/pyradiomics.git to /tmp/pip-req-build-6xfrj3k2
  Running command git clone --filter=blob:none --quiet https://github.com/AIM-Harvard/pyradiomics.git /tmp/pip-req-build-6xfrj3k2
  Resolved https://github.com/AIM-Harvard/pyradiomics.git to commit 8ed579383b44806651c463d5e691f3b2b57522ab
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=2.0 (from pyradiomics==3.1.1.dev111+g8ed579383)
  Using cached numpy-2.3.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting SimpleITK>=2.4.0 (from pyradiomics==3.1.1.dev111+g8ed579383)
  Using cached simpleitk-2.5.2-cp311-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (7.2 kB)
Requirement already satisfied: PyWavelets>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from pyradiomics==3.1.1.dev111+g8ed579383) (1.6.0)
Requirement already satisfied: pykwalify>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from pyradiomics==3.1.1.dev111+g8ed579383) (1.8.0)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (0.6.2)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (2.9.0.post0)
Requirement already satisfied: ruamel.yaml>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (0.18.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (1.17.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from ruamel.yaml>=0.16.0->pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (0.2.14)
Using cached numpy-2.3.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached simpleitk-2.5.2-cp311-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (52.6 MB)
Building wheels for collected packages: pyradiomics
  Building wheel for pyradiomics (pyproject.toml) ... done
  Created wheel for pyradiomics: filename=pyradiomics-3.1.1.dev111+g8ed579383-cp312-cp312-linux_x86_64.whl size=121811 sha256=5d32cbde64f321efd2213b567f25e708e394d600749aca110adf9a569717981a
  Stored in directory: /tmp/pip-ephem-wheel-cache-qretcbi1/wheels/e2/99/a6/b2d774920a9e48d28ec790aa277aa8f49f531d2d6d63cd5c94
Successfully built pyradiomics
Installing collected packages: SimpleITK, numpy, pyradiomics
  Attempting uninstall: SimpleITK
    Found existing installation: SimpleITK 2.3.1
    Uninstalling SimpleITK-2.3.1:
      Successfully uninstalled SimpleITK-2.3.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.4 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.4 which is incompatible.
cupy-cuda12x 13.3.0 requires numpy<2.3,>=1.22, but you have numpy 2.3.4 which is incompatible.
Successfully installed SimpleITK-2.5.2 numpy-2.3.4 pyradiomics-3.1.1.dev111+g8ed579383

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip uninstall -y numpy simpleITK
!pip install numpy==1.26.4
!pip install SimpleITK==2.3.1
import numpy
print("NumPy:", numpy.__version__)
print("SimpleITK:", SimpleITK.Version_VersionString())

Found existing installation: numpy 2.3.4
Uninstalling numpy-2.3.4:
  Successfully uninstalled numpy-2.3.4
Found existing installation: simpleitk 2.5.2
Uninstalling simpleitk-2.5.2:
  Successfully uninstalled simpleitk-2.5.2
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyradiomics 3.1.1.dev111+g8ed579383 requires SimpleITK>=2.4.0, which is not installed.
pyradiomics 3.1.1.dev111+g8ed579383 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

Collecting SimpleITK==2.3.1
  Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.9 kB)
Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (52.7 MB)
Installing collected packages: SimpleITK
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyradiomics 3.1.1.dev111+g8ed579383 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pyradiomics 3.1.1.dev111+g8ed579383 requires SimpleITK>=2.4.0, but you have simpleitk 2.3.1 which is incompatible.
Successfully installed SimpleITK-2.3.1
NumPy: 1.26.4

NameError: name 'SimpleITK' is not defined

In [ ]:
#
import numpy, SimpleITK, radiomics
from radiomics import featureextractor
print("NumPy:", numpy.__version__)
print("SimpleITK:", SimpleITK.Version_VersionString())
print("PyRadiomics:", radiomics.__version__)

NumPy: 1.26.4
SimpleITK: 2.3.1
PyRadiomics: 3.1.1.dev111+g8ed579383

In [ ]:
import glob, os
imgs  = sorted(glob.glob("/content/drive/MyDrive/DSH/Lab-gruppo/dataset1_CS/image_*.nii.gz"))
masks = sorted(glob.glob("/content/drive/MyDrive/DSH/Lab-gruppo/Dataset_2/Maschere/mask_*.nii.gz"))
print("Immagini:", len(imgs))
print("Maschere:", len(masks))
print("Esempio immagini:", [os.path.basename(i) for i in imgs])
print("Esempio maschere:", [os.path.basename(m) for m in masks])

Immagini: 106
Maschere: 41
Esempio immagini: ['image_1.nii.gz', 'image_10.nii.gz', 'image_100.nii.gz', 'image_102.nii.gz', 'image_103.nii.gz', 'image_104.nii.gz', 'image_106.nii.gz', 'image_107.nii.gz', 'image_108.nii.gz', 'image_109.nii.gz', 'image_11.nii.gz', 'image_110.nii.gz', 'image_111.nii.gz', 'image_114.nii.gz', 'image_117.nii.gz', 'image_12.nii.gz', 'image_121.nii.gz', 'image_122.nii.gz', 'image_125.nii.gz', 'image_128.nii.gz', 'image_129.nii.gz', 'image_130.nii.gz', 'image_131.nii.gz', 'image_134.nii.gz', 'image_136.nii.gz', 'image_138.nii.gz', 'image_14.nii.gz', 'image_140.nii.gz', 'image_141.nii.gz', 'image_144.nii.gz', 'image_145.nii.gz', 'image_146.nii.gz', 'image_149.nii.gz', 'image_151.nii.gz', 'image_16.nii.gz', 'image_17.nii.gz', 'image_18.nii.gz', 'image_19.nii.gz', 'image_2.nii.gz', 'image_21.nii.gz', 'image_22.nii.gz', 'image_23.nii.gz', 'image_24.nii.gz', 'image_25.nii.gz', 'image_26.nii.gz', 'image_27.nii.gz', 'image_28.nii.gz', 'image_29.nii.gz', 'image_3.nii.gz', 'image_30.nii.gz', 'image_31.nii.gz', 'image_32.nii.gz', 'image_33.nii.gz', 'image_34.nii.gz', 'image_36.nii.gz', 'image_37.nii.gz', 'image_38.nii.gz', 'image_39.nii.gz', 'image_4.nii.gz', 'image_40.nii.gz', 'image_41.nii.gz', 'image_42.nii.gz', 'image_43.nii.gz', 'image_44.nii.gz', 'image_45.nii.gz', 'image_46.nii.gz', 'image_48.nii.gz', 'image_5.nii.gz', 'image_53.nii.gz', 'image_58.nii.gz', 'image_59.nii.gz', 'image_6.nii.gz', 'image_61.nii.gz', 'image_62.nii.gz', 'image_63.nii.gz', 'image_64.nii.gz', 'image_65.nii.gz', 'image_66.nii.gz', 'image_67.nii.gz', 'image_68.nii.gz', 'image_69.nii.gz', 'image_7.nii.gz', 'image_70.nii.gz', 'image_72.nii.gz', 'image_73.nii.gz', 'image_74.nii.gz', 'image_75.nii.gz', 'image_76.nii.gz', 'image_78.nii.gz', 'image_79.nii.gz', 'image_8.nii.gz', 'image_80.nii.gz', 'image_86.nii.gz', 'image_87.nii.gz', 'image_88.nii.gz', 'image_89.nii.gz', 'image_9.nii.gz', 'image_90.nii.gz', 'image_91.nii.gz', 'image_93.nii.gz', 'image_94.nii.gz', 'image_95.nii.gz', 'image_96.nii.gz', 'image_97.nii.gz', 'image_98.nii.gz', 'image_99.nii.gz']
Esempio maschere: ['mask_100.nii.gz', 'mask_102.nii.gz', 'mask_103.nii.gz', 'mask_107.nii.gz', 'mask_108.nii.gz', 'mask_109.nii.gz', 'mask_111.nii.gz', 'mask_114.nii.gz', 'mask_12.nii.gz', 'mask_125.nii.gz', 'mask_128.nii.gz', 'mask_129.nii.gz', 'mask_130.nii.gz', 'mask_131.nii.gz', 'mask_136.nii.gz', 'mask_140.nii.gz', 'mask_144.nii.gz', 'mask_145.nii.gz', 'mask_146.nii.gz', 'mask_149.nii.gz', 'mask_151.nii.gz', 'mask_17.nii.gz', 'mask_27.nii.gz', 'mask_29.nii.gz', 'mask_33.nii.gz', 'mask_45.nii.gz', 'mask_59.nii.gz', 'mask_6.nii.gz', 'mask_65.nii.gz', 'mask_78.nii.gz', 'mask_79.nii.gz', 'mask_8.nii.gz', 'mask_80.nii.gz', 'mask_86.nii.gz', 'mask_88.nii.gz', 'mask_91.nii.gz', 'mask_93.nii.gz', 'mask_94.nii.gz', 'mask_97.nii.gz', 'mask_98.nii.gz', 'mask_99.nii.gz']

In [ ]:
import os, glob, re, pandas as pd
from radiomics import featureextractor

IN_DIR = "/content/drive/MyDrive/DSH/Lab-gruppo/dataset1_CS"
MASK_DIR = "/content/drive/MyDrive/DSH/Lab-gruppo/Dataset_2/Maschere"
PARAMS = "/content/drive/MyDrive/DSH/Lab-gruppo/Lab2/params.yaml"

# Inizializza l’estrattore (legge params.yaml)
extractor = featureextractor.RadiomicsFeatureExtractor(PARAMS)

rows = []
# Ordina per id numerico
mask_paths = sorted(
    glob.glob(os.path.join(MASK_DIR, "mask_*.nii.gz")),
    key=lambda p: int(re.findall(r"\d+", os.path.basename(p))[0])
)

for mask_path in mask_paths:
    k = int(re.findall(r"\d+", os.path.basename(mask_path))[0])
    img_path = os.path.join(IN_DIR, f"image_{k}.nii.gz")
    if not os.path.exists(img_path):
        print(f"Salto ID {k}: immagine non trovata")
        continue

    result = extractor.execute(img_path, mask_path)
    # Tieni solo le feature (escludi diagnosi/diagnostics)
    feats = {k2: v2 for k2, v2 in result.items() if not k2.startswith("diagnostics")}
    feats["ID"] = k
    rows.append(feats)

df_feats = pd.DataFrame(rows).sort_values("ID").reset_index(drop=True)

# Reorder columns to put 'ID' first
cols = df_feats.columns.tolist()
cols.insert(0, cols.pop(cols.index('ID')))
df_feats = df_feats[cols]

df_feats.to_csv("/content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2.csv", index=False)
print("✅ Salvato: /content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2.csv")
display(df_feats.head())

INFO:radiomics.featureextractor:Loading parameter file /content/drive/MyDrive/DSH/Lab-gruppo/Lab2/params.yaml
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm

✅ Salvato: /content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2.csv

,ID,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,6,0.521400,0.375110,20.593319,54.899365,64.28892958577826,42.12580866278016,61.584171411630045,64.29256386006234,13469.603459040323,...,0.18380238377902564,0.010824254652708006,0.19193441948466028,26.420099900877215,0.0025872979598683976,12.959194696911734,0.00025965776319115686,339.6357729668496,0.05576268783379896,0.044607886335355236
1,8,0.374043,0.313982,26.364130,83.966980,49.90052604933138,79.00385062575297,82.45172186187673,86.97101583760647,26418.30325126648,...,0.09028304898632801,0.00919507251839213,0.272277850337198,51.02597932866289,0.0035231625425961076,24.5527339246461,0.0001317895604662419,468.934795516325,0.12034794320875997,0.021178646339273452
2,12,0.726389,0.528608,8.620020,16.307019,20.91935431043762,13.707320124663317,23.0688930840862,23.927405875964176,688.9913736979166,...,0.6144677044777885,0.029157804174226056,0.18658868181844043,12.495794504866124,0.006791585953690016,1.26152711211178,0.0076026196151953345,116.02788552356658,0.07829070467731199,0.5561773976626693
3,17,0.783355,0.673373,30.395897,45.139791,47.81318713922342,52.47844158952359,53.636737561502144,67.57458698514833,15126.054483572641,...,0.14515947936778822,0.008177273185040343,0.19111453775862125,30.360467054000384,0.0020311892347844424,9.34265419225813,0.0002964283715243303,348.2258961333595,0.04406949205568062,0.05987935405079302
4,27,0.833059,0.339485,7.188657,21.175153,22.651174337162722,23.58387753922489,23.06052628008418,27.700634460895166,954.5389811197916,...,0.14553596034151123,0.01051356127087413,0.2219781631065248,30.079455176338328,0.003507406042082022,0.8776354274476341,0.0037064279749437286,322.4957463766548,0.054810622382307564,0.639928183284916

In [ ]:
from google.colab import auth
import gspread
from google.auth import default

# Authenticate to Google Drive and Google Sheets
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Open the spreadsheet and select the worksheet
try:
    spreadsheet = gc.open("Diagnosi")
    worksheet = spreadsheet.get_worksheet(0)
    # Get all data from the worksheet
    diagnosis_data = worksheet.get_all_records()
    df_diagnosis = pd.DataFrame(diagnosis_data)
    print("✅ Caricato il file Diagnosi.gsheet")
    display(df_diagnosis.head())
except Exception as e:
    print(f"Error loading Google Sheet: {e}")
    df_diagnosis = None

✅ Caricato il file Diagnosi.gsheet

,CASE NUMBER,SEX,AGE,DEFINITIVE DIAGNOSIS,CHALLENGING CASES,CANCER AND DIVERTICULA
0,1,F,59,0,1,0
1,2,M,74,0,1,0
2,3,M,65,0,0,0
3,4,M,73,0,0,0
4,5,F,88,0,0,0

In [ ]:
if df_diagnosis is not None:
    # Rename 'CASE NUMBER' to 'ID' for merging
    df_diagnosis = df_diagnosis.rename(columns={"CASE NUMBER": "ID"})

    # Select only the relevant columns and rename 'DEFINITIVE DIAGNOSIS' to 'class'
    df_diagnosis = df_diagnosis[['ID', 'DEFINITIVE DIAGNOSIS ']].rename(columns={'DEFINITIVE DIAGNOSIS': 'class'})

    # Ensure 'ID' column is of the same type in both dataframes for merging
    #df_diagnosis['ID'] = df_diagnosis['ID'].astype(str)
    #df_feats['ID'] = df_feats['ID'].astype(str)

    # Merge the dataframes
    df_merged = pd.merge(df_feats, df_diagnosis, on='ID', how='left')

    # Save the merged dataframe
    output_csv_path_merged = "/content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2.csv"
    df_merged.to_csv(output_csv_path_merged, index=False)

    print(f"✅ Salvato il file unito con la colonna 'class': {output_csv_path_merged}")
    display(df_merged.head())
else:
    print("Skipping merge as diagnosis data could not be loaded.")

✅ Salvato il file unito con la colonna 'class': /content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2.csv

,ID,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,...,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,DEFINITIVE DIAGNOSIS
0,6,0.521400,0.375110,20.593319,54.899365,64.28892958577826,42.12580866278016,61.584171411630045,64.29256386006234,13469.603459040323,...,0.010824254652708006,0.19193441948466028,26.420099900877215,0.0025872979598683976,12.959194696911734,0.00025965776319115686,339.6357729668496,0.05576268783379896,0.044607886335355236,0
1,8,0.374043,0.313982,26.364130,83.966980,49.90052604933138,79.00385062575297,82.45172186187673,86.97101583760647,26418.30325126648,...,0.00919507251839213,0.272277850337198,51.02597932866289,0.0035231625425961076,24.5527339246461,0.0001317895604662419,468.934795516325,0.12034794320875997,0.021178646339273452,0
2,12,0.726389,0.528608,8.620020,16.307019,20.91935431043762,13.707320124663317,23.0688930840862,23.927405875964176,688.9913736979166,...,0.029157804174226056,0.18658868181844043,12.495794504866124,0.006791585953690016,1.26152711211178,0.0076026196151953345,116.02788552356658,0.07829070467731199,0.5561773976626693,0
3,17,0.783355,0.673373,30.395897,45.139791,47.81318713922342,52.47844158952359,53.636737561502144,67.57458698514833,15126.054483572641,...,0.008177273185040343,0.19111453775862125,30.360467054000384,0.0020311892347844424,9.34265419225813,0.0002964283715243303,348.2258961333595,0.04406949205568062,0.05987935405079302,0
4,27,0.833059,0.339485,7.188657,21.175153,22.651174337162722,23.58387753922489,23.06052628008418,27.700634460895166,954.5389811197916,...,0.01051356127087413,0.2219781631065248,30.079455176338328,0.003507406042082022,0.8776354274476341,0.0037064279749437286,322.4957463766548,0.054810622382307564,0.639928183284916,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd # Import pandas if not already imported

if df_merged is not None:
    # Separate features and the class column
    features = df_merged.drop(columns=['ID', 'DEFINITIVE DIAGNOSIS ']) # Dropping the original class column as well
    class_col = df_merged[['ID', 'DEFINITIVE DIAGNOSIS ']].rename(columns={'DEFINITIVE DIAGNOSIS ': 'class'})

    # Min-Max Scaling
    scaler_minmax = MinMaxScaler()
    features_normalized = scaler_minmax.fit_transform(features)
    df_normalized = pd.DataFrame(features_normalized, columns=features.columns)
    df_normalized = pd.concat([class_col, df_normalized], axis=1) # Add ID and class back

    # Reorder columns for df_normalized
    cols_normalized = df_normalized.columns.tolist()
    cols_normalized.insert(0, cols_normalized.pop(cols_normalized.index('ID')))
    cols_normalized.append(cols_normalized.pop(cols_normalized.index('class')))
    df_normalized = df_normalized[cols_normalized]


    # Z-score Standardization
    scaler_zscore = StandardScaler()
    features_standardized = scaler_zscore.fit_transform(features)
    df_standardized = pd.DataFrame(features_standardized, columns=features.columns)
    df_standardized = pd.concat([class_col, df_standardized], axis=1) # Add ID and class back

    # Reorder columns for df_standardized
    cols_standardized = df_standardized.columns.tolist()
    cols_standardized.insert(0, cols_standardized.pop(cols_standardized.index('ID')))
    cols_standardized.append(cols_standardized.pop(cols_standardized.index('class')))
    df_standardized = df_standardized[cols_standardized]


    # Save to CSV files
    output_csv_path_normalized = "/content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2_normalized.csv"
    df_normalized.to_csv(output_csv_path_normalized, index=False)
    print(f"✅ Salvato il file normalizzato: {output_csv_path_normalized}")

    output_csv_path_standardized = "/content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2_standardized.csv"
    df_standardized.to_csv(output_csv_path_standardized, index=False)
    print(f"✅ Salvato il file standardizzato: {output_csv_path_standardized}")

else:
    print("Skipping scaling and saving as merged data could not be loaded.")

✅ Salvato il file normalizzato: /content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2_normalized.csv
✅ Salvato il file standardizzato: /content/drive/MyDrive/DSH/Lab-gruppo/Lab2/features_dataset2_standardized.csv