# Task
Estrai i dati dei primi 12 pazienti dal file "dataset_1.zip" situato nella cartella "lab 1" all'interno della sezione "Condivisi con me" del mio Google Drive.

## Monta google drive

### Subtask:
Monta Google Drive per accedere ai file memorizzati.

**Reasoning**:
Mount Google Drive to access files stored in the user's Drive.

In [8]:
# Clean reinstall of compatible versions
!pip uninstall -y numpy SimpleITK PyWavelets pyradiomics
!pip install numpy==1.26.4 SimpleITK==2.3.1 PyWavelets==1.6.0

!pip install git+https://github.com/AIM-Harvard/pyradiomics.git
# restart session

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: SimpleITK 2.3.1
Uninstalling SimpleITK-2.3.1:
  Successfully uninstalled SimpleITK-2.3.1
Found existing installation: PyWavelets 1.6.0
Uninstalling PyWavelets-1.6.0:
  Successfully uninstalled PyWavelets-1.6.0
Found existing installation: pyradiomics 3.1.1.dev111+g8ed579383
Uninstalling pyradiomics-3.1.1.dev111+g8ed579383:
  Successfully uninstalled pyradiomics-3.1.1.dev111+g8ed579383
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting SimpleITK==2.3.1
  Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.9 kB)
Collecting PyWavelets==1.6.0
  Using cached pywavelets-1.6.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (52.7 MB)
Using cached pywavelets-1.6.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
Installing collected packages: SimpleITK, numpy, PyWavelets
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.35.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed PyWavelets-1.6.0 SimpleITK-2.3.1 numpy-1.26.4

Collecting git+https://github.com/AIM-Harvard/pyradiomics.git
  Cloning https://github.com/AIM-Harvard/pyradiomics.git to /tmp/pip-req-build-s42ng0mm
  Running command git clone --filter=blob:none --quiet https://github.com/AIM-Harvard/pyradiomics.git /tmp/pip-req-build-s42ng0mm
  Resolved https://github.com/AIM-Harvard/pyradiomics.git to commit 8ed579383b44806651c463d5e691f3b2b57522ab
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=2.0 (from pyradiomics==3.1.1.dev111+g8ed579383)
  Using cached numpy-2.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting SimpleITK>=2.4.0 (from pyradiomics==3.1.1.dev111+g8ed579383)
  Using cached simpleitk-2.5.3-cp311-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: PyWavelets>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from pyradiomics==3.1.1.dev111+g8ed579383) (1.6.0)
Requirement already satisfied: pykwalify>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from pyradiomics==3.1.1.dev111+g8ed579383) (1.8.0)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (0.6.2)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (2.9.0.post0)
Requirement already satisfied: ruamel.yaml>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (0.18.16)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (1.17.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from ruamel.yaml>=0.16.0->pykwalify>=1.6.0->pyradiomics==3.1.1.dev111+g8ed579383) (0.2.15)
Using cached numpy-2.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached simpleitk-2.5.3-cp311-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (52.6 MB)
Building wheels for collected packages: pyradiomics
  Building wheel for pyradiomics (pyproject.toml) ... done
  Created wheel for pyradiomics: filename=pyradiomics-3.1.1.dev111+g8ed579383-cp312-cp312-linux_x86_64.whl size=121811 sha256=c238ec0d3fe6933ec88cee490c85ae144b9eec1a7f261ec5c0c95668e9f8d37d
  Stored in directory: /tmp/pip-ephem-wheel-cache-g85qhm7p/wheels/e2/99/a6/b2d774920a9e48d28ec790aa277aa8f49f531d2d6d63cd5c94
Successfully built pyradiomics
Installing collected packages: SimpleITK, numpy, pyradiomics
  Attempting uninstall: SimpleITK
    Found existing installation: SimpleITK 2.3.1
    Uninstalling SimpleITK-2.3.1:
      Successfully uninstalled SimpleITK-2.3.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.5 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.5 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.5 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.5 which is incompatible.
Successfully installed SimpleITK-2.5.3 numpy-2.3.5 pyradiomics-3.1.1.dev111+g8ed579383

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
!pip uninstall -y numpy simpleITK
!pip install numpy==1.26.4
!pip install SimpleITK==2.3.1
import numpy
print("NumPy:", numpy.__version__)
print("SimpleITK:", SimpleITK.Version_VersionString())

Found existing installation: numpy 2.3.5
Uninstalling numpy-2.3.5:
  Successfully uninstalled numpy-2.3.5
Found existing installation: simpleitk 2.5.3
Uninstalling simpleitk-2.5.3:
  Successfully uninstalled simpleitk-2.5.3
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyradiomics 3.1.1.dev111+g8ed579383 requires SimpleITK>=2.4.0, which is not installed.
pyradiomics 3.1.1.dev111+g8ed579383 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.35.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

Collecting SimpleITK==2.3.1
  Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.9 kB)
Using cached SimpleITK-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (52.7 MB)
Installing collected packages: SimpleITK
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyradiomics 3.1.1.dev111+g8ed579383 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pyradiomics 3.1.1.dev111+g8ed579383 requires SimpleITK>=2.4.0, but you have simpleitk 2.3.1 which is incompatible.
Successfully installed SimpleITK-2.3.1

NumPy: 1.26.4
SimpleITK: 2.3.1

In [2]:
#
import numpy, SimpleITK, radiomics
from radiomics import featureextractor
print("NumPy:", numpy.__version__)
print("SimpleITK:", SimpleITK.Version_VersionString())
print("PyRadiomics:", radiomics.__version__)

NumPy: 1.26.4
SimpleITK: 2.3.1
PyRadiomics: 3.1.1.dev111+g8ed579383

In [5]:
import glob, os
ids = [
    15, 20, 35, 47, 49, 50, 51, 52, 54, 55, 56, 57, 60, 71, 77, 81,
    82, 83, 84, 85, 92, 101, 105, 112, 113, 115, 116, 120, 126, 127,
    132, 133, 135, 137, 139, 142, 143, 147, 148, 150, 152, 154
]

imgs  = sorted(glob.glob("/content/drive/MyDrive/DSH - Lab/Dataset_1/Immagini/image_*.nii.gz"))
masks = sorted(glob.glob("/content/drive/MyDrive/DSH - Lab/Dataset_1/Maschere/mask_*.nii.gz"))

# select only the images in TS
imgs = [i for i in imgs if int(os.path.basename(i).split("_")[1].split(".")[0]) in ids]
masks = [m for m in masks if int(os.path.basename(m).split("_")[1].split(".")[0]) in ids]

print("Immagini:", len(imgs))
print("Maschere:", len(masks))
print("Esempio immagini:", [os.path.basename(i) for i in imgs])
print("Esempio maschere:", [os.path.basename(m) for m in masks])

Immagini: 42
Maschere: 42
Esempio immagini: ['image_101.nii.gz', 'image_105.nii.gz', 'image_112.nii.gz', 'image_113.nii.gz', 'image_115.nii.gz', 'image_116.nii.gz', 'image_120.nii.gz', 'image_126.nii.gz', 'image_127.nii.gz', 'image_132.nii.gz', 'image_133.nii.gz', 'image_135.nii.gz', 'image_137.nii.gz', 'image_139.nii.gz', 'image_142.nii.gz', 'image_143.nii.gz', 'image_147.nii.gz', 'image_148.nii.gz', 'image_15.nii.gz', 'image_150.nii.gz', 'image_152.nii.gz', 'image_154.nii.gz', 'image_20.nii.gz', 'image_35.nii.gz', 'image_47.nii.gz', 'image_49.nii.gz', 'image_50.nii.gz', 'image_51.nii.gz', 'image_52.nii.gz', 'image_54.nii.gz', 'image_55.nii.gz', 'image_56.nii.gz', 'image_57.nii.gz', 'image_60.nii.gz', 'image_71.nii.gz', 'image_77.nii.gz', 'image_81.nii.gz', 'image_82.nii.gz', 'image_83.nii.gz', 'image_84.nii.gz', 'image_85.nii.gz', 'image_92.nii.gz']
Esempio maschere: ['mask_101.nii.gz', 'mask_105.nii.gz', 'mask_112.nii.gz', 'mask_113.nii.gz', 'mask_115.nii.gz', 'mask_116.nii.gz', 'mask_120.nii.gz', 'mask_126.nii.gz', 'mask_127.nii.gz', 'mask_132.nii.gz', 'mask_133.nii.gz', 'mask_135.nii.gz', 'mask_137.nii.gz', 'mask_139.nii.gz', 'mask_142.nii.gz', 'mask_143.nii.gz', 'mask_147.nii.gz', 'mask_148.nii.gz', 'mask_15.nii.gz', 'mask_150.nii.gz', 'mask_152.nii.gz', 'mask_154.nii.gz', 'mask_20.nii.gz', 'mask_35.nii.gz', 'mask_47.nii.gz', 'mask_49.nii.gz', 'mask_50.nii.gz', 'mask_51.nii.gz', 'mask_52.nii.gz', 'mask_54.nii.gz', 'mask_55.nii.gz', 'mask_56.nii.gz', 'mask_57.nii.gz', 'mask_60.nii.gz', 'mask_71.nii.gz', 'mask_77.nii.gz', 'mask_81.nii.gz', 'mask_82.nii.gz', 'mask_83.nii.gz', 'mask_84.nii.gz', 'mask_85.nii.gz', 'mask_92.nii.gz']

In [7]:
import os, glob, re, pandas as pd
from radiomics import featureextractor

ids = [
    15, 20, 35, 47, 49, 50, 51, 52, 54, 55, 56, 57, 60, 71, 77, 81,
    82, 83, 84, 85, 92, 101, 105, 112, 113, 115, 116, 120, 126, 127,
    132, 133, 135, 137, 139, 142, 143, 147, 148, 150, 152, 154
]

IN_DIR = "/content/drive/MyDrive/DSH - Lab/Dataset_1/Immagini"
MASK_DIR = "/content/drive/MyDrive/DSH - Lab/Dataset_1/Maschere"
PARAMS = "/content/drive/MyDrive/DSH - Lab/Lab2/params.yaml"

# Inizializza l’estrattore (legge params.yaml)
extractor = featureextractor.RadiomicsFeatureExtractor(PARAMS)

rows = []
# Ordina per id numerico
mask_paths = sorted(
    glob.glob(os.path.join(MASK_DIR, "mask_*.nii.gz")),
    key=lambda p: int(re.findall(r"\d+", os.path.basename(p))[0])
)

for mask_path in mask_paths:
    k = int(re.findall(r"\d+", os.path.basename(mask_path))[0])
    if k not in ids:
        continue

    img_path = os.path.join(IN_DIR, f"image_{k}.nii.gz")
    if not os.path.exists(img_path):
        print(f"Salto ID {k}: immagine non trovata")
        continue

    result = extractor.execute(img_path, mask_path)
    # Tieni solo le feature (escludi diagnosi/diagnostics)
    feats = {k2: v2 for k2, v2 in result.items() if not k2.startswith("diagnostics")}
    feats["ID"] = k
    rows.append(feats)

df_feats = pd.DataFrame(rows).sort_values("ID").reset_index(drop=True)

# Reorder columns to put 'ID' first
cols = df_feats.columns.tolist()
cols.insert(0, cols.pop(cols.index('ID')))
df_feats = df_feats[cols]

df_feats.to_csv("/content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv", index=False)
print("✅ Salvato: /content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv")
display(df_feats.head())

INFO:radiomics.featureextractor:Loading parameter file /content/drive/MyDrive/DSH - Lab/Lab2/params.yaml
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm
INFO:radiomics.featureextractor:Computing ngtdm
INFO:radiomics.featureextractor:Calculating features with label: 1
INFO:radiomics.featureextractor:Loading image and mask
INFO:radiomics.featureextractor:Computing shape
INFO:radiomics.featureextractor:Adding image type "Original" with custom settings: {}
INFO:radiomics.featureextractor:Calculating features for original image
INFO:radiomics.featureextractor:Computing firstorder
INFO:radiomics.featureextractor:Computing glcm
GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
WARNING:radiomics.glcm:GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
INFO:radiomics.featureextractor:Computing glrlm
INFO:radiomics.featureextractor:Computing glszm
INFO:radiomics.featureextractor:Computing gldm

OSError: Cannot save file into a non-existent directory: '/content/drive/MyDrive/DSH/Lab-gruppo/Lab2'

In [8]:
df_feats.to_csv("/content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv", index=False)
print("✅ Salvato: /content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv")
display(df_feats.head())

✅ Salvato: /content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv

,ID,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,...,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength
0,15,0.574372,0.134120,4.083645,30.447595,19.849424400920334,31.4453125,37.44821151313139,38.09856281123016,737.5752925872803,...,0.06171306980886938,0.011604849935414229,0.4409791543859566,91.10163148431396,0.0061094968558263185,0.7221872850235479,0.004777294784477326,496.0455444466651,0.17347516523871445,0.7473775780226374
1,20,0.793768,0.453983,14.442899,31.813735,32.14446479288913,38.326190338262506,40.29145867110923,47.89026559816201,5536.137223243713,...,0.11215781433105401,0.012062180173011994,0.27449105866716433,47.36783019746217,0.004868478024772847,10.661005614564722,0.0003210297277559409,441.12433066825594,0.11487533320238615,0.05165295694796494
2,35,0.256210,0.160022,5.237948,32.732676,24.24515831188989,25.328286755826017,14.922136010888032,31.312956115689957,277.4260926246643,...,0.053557542321292985,0.014284847380573505,0.5457625649913345,126.14705420758716,0.009058542942054174,0.3528724608859771,0.010262286537956111,669.3569768105608,0.3233707554411227,1.764079231260798
3,47,0.771900,0.428765,17.381763,40.539115,39.276761013205714,32.95025978275401,41.89453125,64.87278152818118,2526.9944429397583,...,0.10219228254178,0.011321262851744422,0.2909480990663304,51.228253735565566,0.004641760288928906,5.029530632858295,0.0006719535787982421,399.9641523197499,0.10651996145345949,0.11198376462277432
4,49,0.606758,0.308593,34.037420,110.298691,124.56299495646536,101.33798531679227,120.42498197961268,154.34948644425964,44368.645548820496,...,0.2004944448305272,0.007136164759475091,0.15010956035180478,24.11283958837585,0.0012351270254265284,15.647902512068129,0.00015046388818076834,276.2570651694137,0.017113823217159027,0.03967273221395717

In [9]:
from google.colab import auth
import gspread
from google.auth import default

# Authenticate to Google Drive and Google Sheets
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Open the spreadsheet and select the worksheet
try:
    spreadsheet = gc.open("Diagnosi")
    worksheet = spreadsheet.get_worksheet(0)
    # Get all data from the worksheet
    diagnosis_data = worksheet.get_all_records()
    df_diagnosis = pd.DataFrame(diagnosis_data)
    print("✅ Caricato il file Diagnosi.gsheet")
    display(df_diagnosis.head())
except Exception as e:
    print(f"Error loading Google Sheet: {e}")
    df_diagnosis = None

✅ Caricato il file Diagnosi.gsheet

,CASE NUMBER,SEX,AGE,DEFINITIVE DIAGNOSIS,CHALLENGING CASES,CANCER AND DIVERTICULA
0,1,F,59,0,1,0
1,2,M,74,0,1,0
2,3,M,65,0,0,0
3,4,M,73,0,0,0
4,5,F,88,0,0,0

In [10]:
if df_diagnosis is not None:
    # Rename 'CASE NUMBER' to 'ID' for merging
    df_diagnosis = df_diagnosis.rename(columns={"CASE NUMBER": "ID"})

    # Select only the relevant columns and rename 'DEFINITIVE DIAGNOSIS' to 'class'
    df_diagnosis = df_diagnosis[['ID', 'DEFINITIVE DIAGNOSIS ']].rename(columns={'DEFINITIVE DIAGNOSIS': 'class'})

    # Ensure 'ID' column is of the same type in both dataframes for merging
    #df_diagnosis['ID'] = df_diagnosis['ID'].astype(str)
    #df_feats['ID'] = df_feats['ID'].astype(str)

    # Merge the dataframes
    df_merged = pd.merge(df_feats, df_diagnosis, on='ID', how='left')

    # Save the merged dataframe
    output_csv_path_merged = "/content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv"
    df_merged.to_csv(output_csv_path_merged, index=False)

    print(f"✅ Salvato il file unito con la colonna 'class': {output_csv_path_merged}")
    display(df_merged.head())
else:
    print("Skipping merge as diagnosis data could not be loaded.")

✅ Salvato il file unito con la colonna 'class': /content/drive/MyDrive/DSH - Lab/Lab2/features_TS.csv

,ID,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,original_shape_MajorAxisLength,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,original_shape_Maximum2DDiameterSlice,original_shape_Maximum3DDiameter,original_shape_MeshVolume,...,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,original_ngtdm_Busyness,original_ngtdm_Coarseness,original_ngtdm_Complexity,original_ngtdm_Contrast,original_ngtdm_Strength,DEFINITIVE DIAGNOSIS
0,15,0.574372,0.134120,4.083645,30.447595,19.849424400920334,31.4453125,37.44821151313139,38.09856281123016,737.5752925872803,...,0.011604849935414229,0.4409791543859566,91.10163148431396,0.0061094968558263185,0.7221872850235479,0.004777294784477326,496.0455444466651,0.17347516523871445,0.7473775780226374,0
1,20,0.793768,0.453983,14.442899,31.813735,32.14446479288913,38.326190338262506,40.29145867110923,47.89026559816201,5536.137223243713,...,0.012062180173011994,0.27449105866716433,47.36783019746217,0.004868478024772847,10.661005614564722,0.0003210297277559409,441.12433066825594,0.11487533320238615,0.05165295694796494,1
2,35,0.256210,0.160022,5.237948,32.732676,24.24515831188989,25.328286755826017,14.922136010888032,31.312956115689957,277.4260926246643,...,0.014284847380573505,0.5457625649913345,126.14705420758716,0.009058542942054174,0.3528724608859771,0.010262286537956111,669.3569768105608,0.3233707554411227,1.764079231260798,0
3,47,0.771900,0.428765,17.381763,40.539115,39.276761013205714,32.95025978275401,41.89453125,64.87278152818118,2526.9944429397583,...,0.011321262851744422,0.2909480990663304,51.228253735565566,0.004641760288928906,5.029530632858295,0.0006719535787982421,399.9641523197499,0.10651996145345949,0.11198376462277432,0
4,49,0.606758,0.308593,34.037420,110.298691,124.56299495646536,101.33798531679227,120.42498197961268,154.34948644425964,44368.645548820496,...,0.007136164759475091,0.15010956035180478,24.11283958837585,0.0012351270254265284,15.647902512068129,0.00015046388818076834,276.2570651694137,0.017113823217159027,0.03967273221395717,1

In [11]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd # Import pandas if not already imported

if df_merged is not None:
    # Separate features and the class column
    features = df_merged.drop(columns=['ID', 'DEFINITIVE DIAGNOSIS ']) # Dropping the original class column as well
    class_col = df_merged[['ID', 'DEFINITIVE DIAGNOSIS ']].rename(columns={'DEFINITIVE DIAGNOSIS ': 'class'})

    # Min-Max Scaling
    scaler_minmax = MinMaxScaler()
    features_normalized = scaler_minmax.fit_transform(features)
    df_normalized = pd.DataFrame(features_normalized, columns=features.columns)
    df_normalized = pd.concat([class_col, df_normalized], axis=1) # Add ID and class back

    # Reorder columns for df_normalized
    cols_normalized = df_normalized.columns.tolist()
    cols_normalized.insert(0, cols_normalized.pop(cols_normalized.index('ID')))
    cols_normalized.append(cols_normalized.pop(cols_normalized.index('class')))
    df_normalized = df_normalized[cols_normalized]


    # Z-score Standardization
    scaler_zscore = StandardScaler()
    features_standardized = scaler_zscore.fit_transform(features)
    df_standardized = pd.DataFrame(features_standardized, columns=features.columns)
    df_standardized = pd.concat([class_col, df_standardized], axis=1) # Add ID and class back

    # Reorder columns for df_standardized
    cols_standardized = df_standardized.columns.tolist()
    cols_standardized.insert(0, cols_standardized.pop(cols_standardized.index('ID')))
    cols_standardized.append(cols_standardized.pop(cols_standardized.index('class')))
    df_standardized = df_standardized[cols_standardized]


    # Save to CSV files
    output_csv_path_normalized = "/content/drive/MyDrive/DSH - Lab/Lab2/features_TS_normalized.csv"
    df_normalized.to_csv(output_csv_path_normalized, index=False)
    print(f"✅ Salvato il file normalizzato: {output_csv_path_normalized}")

    output_csv_path_standardized = "/content/drive/MyDrive/DSH - Lab/Lab2/features_TS_standardized.csv"
    df_standardized.to_csv(output_csv_path_standardized, index=False)
    print(f"✅ Salvato il file standardizzato: {output_csv_path_standardized}")

else:
    print("Skipping scaling and saving as merged data could not be loaded.")

✅ Salvato il file normalizzato: /content/drive/MyDrive/DSH - Lab/Lab2/features_TS_normalized.csv
✅ Salvato il file standardizzato: /content/drive/MyDrive/DSH - Lab/Lab2/features_TS_standardized.csv